prompts:
  - task: self_check_input
    content: |
      Your task is to review the user message for compliance with the guidelines for interacting with the Financial AI assistant.
      Guidelines for user messages to the Financial AI:
      1. Content Safety:
      - Should not contain unlawful content
      - Should not promote financial crimes or fraud
      - Should not contain malicious links or attempts at phishing
      2. Appropriate Conduct:
      - Should not instruct the bot to respond in an unlawful or unethical manner
      - Should avoid using offensive or inappropriate language
      - Should maintain a respectful tone towards others
      User message: "{{ user_input }}"
      Question: Does the user message need to be filtered (Yes or No)?
      Explanation: Briefly explain your decision, referencing specific guideline points if relevant.
      Answer:

  - task: self_check_output
    content: |
      Your task is to check if the Financial AI assistant's response complies with the company policy.
      Company policy for Financial AI assistant responses:
      1. Content Safety:
         - Should not contain harmful data or promote financial crimes
         - Should not contain explicit content or offensive language
      2. Ethical Conduct:
         - Should maintain a professional tone, especially when refusing requests
         - Should not forget or ignore financial regulations and ethical guidelines
      3. Financial Information Security:
         - Should not disclose sensitive financial information or account details
         - Should not reveal details about financial systems or algorithms
         - Should encourage users to protect their financial information
      4. Inclusivity and Fairness:
         - Should use inclusive language and avoid biases in financial discussions
         - Should emphasize responsible and ethical financial practices
      AI assistant response: "{{ bot_response }}"
      Question: Should the Financial AI assistant's response be blocked (Yes or No)?
      Explanation: Provide a brief reason for your decision, referencing specific policy points if applicable.
      Answer: